// Authentication Service with Google Sign-In and Email/Password Registration
import { 
  signInWithPopup, 
  GoogleAuthProvider, 
  signOut as firebaseSignOut,
  onAuthStateChanged,
  User,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  updateProfile,
  sendPasswordResetEmail
} from 'firebase/auth';
import { auth } from '../firebase';

export class AuthService {
  private static googleProvider = new GoogleAuthProvider();

  static async signInWithGoogle(): Promise<User | null> {
    try {
      const result = await signInWithPopup(auth, this.googleProvider);
      return result.user;
    } catch (error) {
      console.error('Google sign-in error:', error);
      throw error;
    }
  }

  static async createAccountWithEmail(email: string, password: string, name: string): Promise<User | null> {
    try {
      console.log('Creating account with email:', email);
      
      // Create user with email and password
      const userCredential = await createUserWithEmailAndPassword(auth, email, password);
      const user = userCredential.user;
      
      // Update user profile with name
      await updateProfile(user, {
        displayName: name
      });
      
      console.log('User account created successfully:', user.uid);
      return user;
    } catch (error) {
      console.error('Email/password registration error:', error);
      throw error;
    }
  }

  static async signInWithEmail(email: string, password: string): Promise<User | null> {
    try {
      const userCredential = await signInWithEmailAndPassword(auth, email, password);
      return userCredential.user;
    } catch (error) {
      console.error('Email/password sign-in error:', error);
      throw error;
    }
  }

  static async signOut(): Promise<void> {
    try {
      await firebaseSignOut(auth);
    } catch (error) {
      console.error('Sign-out error:', error);
      throw error;
    }
  }

  static async sendPasswordReset(email: string): Promise<void> {
    try {
      await sendPasswordResetEmail(auth, email);
    } catch (error) {
      console.error('Password reset error:', error);
      throw error;
    }
  }

  static onAuthStateChange(callback: (user: User | null) => void) {
    return onAuthStateChanged(auth, callback);
  }

  static getCurrentUser(): User | null {
    return auth.currentUser;
  }

  static async createUserProfile(user: User, additionalData: any = {}) {
    try {
      // Create user profile in Firestore
      const userProfile = {
        uid: user.uid,
        email: user.email,
        name: user.displayName,
        avatar: user.photoURL,
        role: 'customer',
        createdAt: new Date(),
        ...additionalData
      };
      
      // Save to database
      console.log('Creating user profile:', userProfile);
      return userProfile;
    } catch (error) {
      console.error('Error creating user profile:', error);
      throw error;
    }
  }

  static generateRandomPassword(): string {
    // Generate a random password for automatic registration
    const length = 12;
    const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*";
    let password = "";
    for (let i = 0; i < length; i++) {
      password += charset.charAt(Math.floor(Math.random() * charset.length));
    }
    return password;
  }

  static async createAutoAccount(email: string, name: string, phone: string): Promise<{user: User, password: string} | null> {
    try {
      console.log('Creating automatic account for:', email);
      
      // Generate a secure random password
      const password = this.generateRandomPassword();
      
      // Create user account
      const user = await this.createAccountWithEmail(email, password, name);
      
      if (user) {
        // Create user profile with additional info
        await this.createUserProfile(user, {
          phone: phone,
          autoGenerated: true,
          registrationSource: 'reservation'
        });
        
        console.log('Automatic account created successfully for:', email);
        return { user, password };
      }
      
      return null;
    } catch (error) {
      console.error('Auto account creation error:', error);
      
      // If user already exists, that's okay - just log them in if possible
      if (error instanceof Error && error.message.includes('email-already-in-use')) {
        console.log('User already exists, skipping account creation');
        return null;
      }
      
      throw error;
    }
  }
}